// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-FxbBTyMQr2CT8mX3VvCsYJu1mUTQrwg',
    appId: '1:1011527282166:web:4128b09e6584e676d56bd7',
    messagingSenderId: '1011527282166',
    projectId: 'earalyze',
    authDomain: 'earalyze.firebaseapp.com',
    storageBucket: 'earalyze.firebasestorage.app',
    measurementId: 'G-MBKPZZHSHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYmSqpClV8FKExckLZHOcDxUWLDRxWJq0',
    appId: '1:1011527282166:android:6286a8767eb8da56d56bd7',
    messagingSenderId: '1011527282166',
    projectId: 'earalyze',
    storageBucket: 'earalyze.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACOp5Hu6Nqko8ouPhb81a5mkQCt0wpFtY',
    appId: '1:1011527282166:ios:ba828a3f3d02feaed56bd7',
    messagingSenderId: '1011527282166',
    projectId: 'earalyze',
    storageBucket: 'earalyze.firebasestorage.app',
    iosBundleId: 'com.example.earalyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACOp5Hu6Nqko8ouPhb81a5mkQCt0wpFtY',
    appId: '1:1011527282166:ios:ba828a3f3d02feaed56bd7',
    messagingSenderId: '1011527282166',
    projectId: 'earalyze',
    storageBucket: 'earalyze.firebasestorage.app',
    iosBundleId: 'com.example.earalyze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-FxbBTyMQr2CT8mX3VvCsYJu1mUTQrwg',
    appId: '1:1011527282166:web:f02436f3a9588b10d56bd7',
    messagingSenderId: '1011527282166',
    projectId: 'earalyze',
    authDomain: 'earalyze.firebaseapp.com',
    storageBucket: 'earalyze.firebasestorage.app',
    measurementId: 'G-0WQNZNH8BX',
  );
}
